# -*- coding: utf-8 -*-
"""Tp1-PID.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15n_XlXIjm2gVmCbmY4JTUoxRhGPZ__5-

Abrir imagen
"""

import numpy as np 
import matplotlib.pyplot as plt

"""Imageio proporciona una variedad de imágenes de ejemplo, que se pueden utilizar"""

import imageio

#imagepath="‪/content/pngwing.png"

#from PIL import Image

"""La función imread devuelve un array con la forma MxN para las imágenes en escala de grises, MxNx3 para las imágenes RGB, y MxNx4 para las imágenes RGBA, donde M es el alto y N es el ancho de la imagen."""

image = imageio.imread('imageio:chelsea.png')

plt.imshow(image)

print(image)

print(image.shape)

plt.imshow(image[0:300, 0:451])
plt.show()

opr=(image*0.01)

plt.imshow(opr)
plt.show()

sum=0.7*image+0.3*opr

plt.imshow(opr)
plt.show()

"""Cambiar una imagen"""

R, G, B = image[:,:,0], image[:,:,1], image[:,:,2]

#imgGray = 0.2989 * R + 0.5870 * G + 0.1140 * B

print(R)

print(R.shape)

imgGray =   R +  G + B

print(imgGray.shape)

plt.imshow(B)

print(image.shape)

plt.imshow(imgGray, cmap='summer')

plt.imshow(imgGray, cmap='gray')
plt.show()

"""Guardar imagen

"""

import matplotlib.image as mpimg

mpimg.imsave("tp1PID.png", image)